"""
Dataclasses used in scigraph_util

These were originally autogenerated from the biolink-api
marshmallow definitions

See original classes here:
https://raw.githubusercontent.com/biolink/biolink-api/1e81503/biomodel/core.py
"""

from dataclasses import dataclass, field
from typing import List


@dataclass
class NamedObject:
    """
    NamedObject

    Arguments
    ---------
     id :

         ID or CURIE e.g. MGI:1201606

     label :

         RDFS Label

     iri :

         IRI

     category :

         Type of object

     description :

         Description (or definition) of an object

     types :

         Type of object (direct)

     synonyms :

         list of synonyms or alternate labels

     replaced_by :

         Direct 1:1 replacement (if named object is obsoleted)

     consider :

         Potential replacement object (if named object is obsoleted)
    """
    id: str = None
    label: str = None
    iri: str = None
    category: str = None
    description: str = None
    types: List[str] = None
    synonyms: List[str] = None
    deprecated: bool = None
    replaced_by: List[str] = None
    consider: List[str] = None


@dataclass
class Taxon:
    id: str = None
    label: str = None


@dataclass
class BioObject(NamedObject):
    """
    BioObject

    Superclass: NamedObject
    """

    taxon: Taxon = None
    association_counts: int = None
    xrefs: List[str] = None


@dataclass
class Disease(BioObject):
    inheritance: List[NamedObject] = field(default_factory=list)
    clinical_modifiers: List[NamedObject] = field(default_factory=list)


@dataclass
class AbstractPropertyValue:
    """
    AbstractPropertyValue

    Arguments
    ---------
     val :

         value part

     pred :

         predicate (attribute) part

     xrefs :

         Xrefs provenance for property-value
    """

    val: str
    pred: str
    xrefs: List[str]


@dataclass
class SynonymPropertyValue(AbstractPropertyValue):
    """
    SynonymPropertyValue

    Superclass: AbstractPropertyValue
    """
    id: str = None
