on:
  pull_request:
    branches:
      - master
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.10", "3.11" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        name: setup python environment
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest
      - name: run make on rules
        # reminder: please run `make travis_test_full` locally to include slow running tests not suitable for CI
        run: make travis_test
